/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface MockContractInterface extends Interface {
  getFunction(nameOrSignature: "adj" | "fail" | "success"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "adj",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fail", values?: undefined): string;
  encodeFunctionData(functionFragment: "success", values?: undefined): string;

  decodeFunctionResult(functionFragment: "adj", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fail", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "success", data: BytesLike): Result;
}

export interface MockContract extends BaseContract {
  connect(runner?: ContractRunner | null): MockContract;
  waitForDeployment(): Promise<this>;

  interface: MockContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adj: TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenAAmt: BigNumberish,
      tokenB: AddressLike,
      tokenBAmt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  fail: TypedContractMethod<[], [void], "view">;

  success: TypedContractMethod<[], [void], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adj"
  ): TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenAAmt: BigNumberish,
      tokenB: AddressLike,
      tokenBAmt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(nameOrSignature: "fail"): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "success"
  ): TypedContractMethod<[], [void], "view">;

  filters: {};
}
