/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockAaveSol from "./mock_aave.sol";
export * as mockAtokenSol from "./mock_atoken.sol";
export * as mockCoinSol from "./mock_coin.sol";
export * as mockContractSol from "./mock_contract.sol";
export * as mockDeployerSol from "./mock_deployer.sol";
