/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockAaveSol from "./mock_aave.sol";
export type { mockAaveSol };
import type * as mockAtokenSol from "./mock_atoken.sol";
export type { mockAtokenSol };
import type * as mockCoinSol from "./mock_coin.sol";
export type { mockCoinSol };
import type * as mockContractSol from "./mock_contract.sol";
export type { mockContractSol };
import type * as mockDeployerSol from "./mock_deployer.sol";
export type { mockDeployerSol };
