/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockAaveAddressProvider } from "./MockAaveAddressProvider";
export type { MockAavePool } from "./MockAavePool";
export type { MockAaveRegistry } from "./MockAaveRegistry";
