/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as deployer from "./deployer";
export type { deployer };
import type * as vaultSol from "./vault.sol";
export type { vaultSol };
import type * as vaultTokenSol from "./vault_token.sol";
export type { vaultTokenSol };
