/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aaveDeployerSol from "./aave_deployer.sol";
export type { aaveDeployerSol };
import type * as deployerInterfaceSol from "./deployer_interface.sol";
export type { deployerInterfaceSol };
